config/routes.rb
Rails.application.routes.draw do

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root 'home#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products,          only: [:show]
    resources :categories,        only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_product.html.erb
<%= render partial: 'shared/select_div_tag',
            locals: { where_from: where_from } %>
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag product.display_image.attachment(:product) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to products_was_filtered? ? potepan_product_path(product.product.id) :
                                           potepan_product_path(product.id) do %>
        <h5><%= product.name %></h5>
        <% if products_was_filtered? %>
          <%= render partial: 'shared/type_and_value',
                      locals: { variant: product } %>
        <% end %>
        <h3><%= product.display_price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_select_div_tag.html.erb
<% case where_from %>
<% when "_related_product.html.erb" %>
  <div class="col-md-3 col-sm-6 col-xs-12">
<% when "_grid.html.erb" %>
  <div class="col-sm-4 col-xs-12">
<% when "_new_product.html.erb" %>
  <div class="slide">
<% end %>

app/views/shared/_type_and_value.html.erb
<% type_and_values = return_type_and_values(variant) %>
<% type_and_values.each do |type_and_value| %>
  <ul>
    <li><%= type_and_value.join(": ") %></li>
  </ul>
<% end %>